language: python
python:
  - 3.8
  - 3.7
  - 3.6

env:
  global:
    - MPLBACKEND=agg

install:
  - pip install -U pytest
  - make dev-install

script:
  - make test
  - make test-pelican

after_success: bash <(curl -s https://codecov.io/bash)
